# Generated by Django 3.2.16 on 2023-03-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0125_merge_20221108_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitygroupmembership',
            name='group',
        ),
        migrations.DeleteModel(
            name='SecurityGroup',
        ),
        migrations.DeleteModel(
            name='SecurityGroupMembership',
        ),
    ]
