# Generated by Django 3.2.16 on 2023-02-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0125_merge_20221108_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitiveprocess',
            options={'ordering': ('modified_at',), 'verbose_name': 'Competitive Process', 'verbose_name_plural': 'Competitive Processes'},
        ),
    ]
