# Generated by Django 3.2.16 on 2023-03-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0126_alter_competitiveprocess_options'),
        ('leaseslicensing', '0126_auto_20230310_1217'),
    ]

    operations = [
    ]
