# Generated by Django 3.2.18 on 2023-03-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0127_merge_20230313_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='lodgement_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
