# Generated by Django 3.2.18 on 2023-03-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0129_organisationrequest_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='lodgement_number',
        ),
        migrations.AddField(
            model_name='organisationrequest',
            name='lodgement_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
