# Generated by Django 3.2.18 on 2023-03-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0130_auto_20230320_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisation_requests', to='leaseslicensing.organisation'),
        ),
    ]
