# Generated by Django 3.2.18 on 2023-03-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0131_alter_organisationrequest_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='assigned_officer',
            field=models.IntegerField(null=True),
        ),
    ]
