# Generated by Django 3.2.18 on 2023-03-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0133_auto_20230321_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='customer_status',
            field=models.CharField(choices=[('due', 'Due'), ('future', 'Future'), ('with_assessor', 'Under Review'), ('approved', 'Approved'), ('discarded', 'Discarded'), ('overdue', 'Overdue')], default='future', max_length=20),
        ),
    ]
