# Generated by Django 3.2.18 on 2023-03-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0133_auto_20230321_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequirement',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.referral'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='customer_status',
            field=models.CharField(choices=[('due', 'Due'), ('future', 'Future'), ('with_assessor', 'Under Review'), ('approved', 'Approved'), ('discarded', 'Discarded'), ('overdue', 'Overdue')], default='future', max_length=20),
        ),
    ]
