# Generated by Django 3.2.18 on 2023-03-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0134_auto_20230324_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequirement',
            name='source',
            field=models.IntegerField(null=True),
        ),
    ]
