# Generated by Django 3.2.18 on 2023-03-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0134_auto_20230323_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_abn',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='Ledger Organisation ABN'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(default='', editable=False, max_length=255, verbose_name='Ledger Organisation Name'),
        ),
    ]
