# Generated by Django 3.2.18 on 2023-03-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0135_auto_20230323_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_email',
            field=models.EmailField(blank=True, editable=False, max_length=254, null=True, verbose_name='Ledger Organisation Email'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation',
            field=models.IntegerField(unique=True, verbose_name='Ledger Organisation ID'),
        ),
    ]
