# Generated by Django 3.2.18 on 2023-03-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0136_auto_20230327_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationcontact',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
