# Generated by Django 3.2.18 on 2023-03-28 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0135_proposalrequirement_source'),
        ('leaseslicensing', '0137_organisationcontact_user'),
    ]

    operations = [
    ]
