# Generated by Django 3.2.18 on 2023-04-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0138_merge_20230328_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'verbose_name': 'Lease/License'},
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='organisation_abn',
            new_name='ledger_organisation_abn',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='organisation_email',
            new_name='ledger_organisation_email',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='organisation',
            new_name='ledger_organisation_id',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='organisation_name',
            new_name='ledger_organisation_name',
        ),
    ]
