# Generated by Django 3.2.18 on 2023-03-30 04:51

from django.db import migrations, models
import django.db.models.deletion
import leaseslicensing.components.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0140_emailuseraction_emailuserlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUserLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, upload_to=leaseslicensing.components.users.models.email_user_comms_log_document_upload_location)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leaseslicensing.emailuserlogentry')),
            ],
        ),
    ]
