# Generated by Django 3.2.18 on 2023-04-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0139_auto_20230403_1009'),
        ('leaseslicensing', '0142_auto_20230330_1319'),
    ]

    operations = [
    ]
