# Generated by Django 3.2.18 on 2023-04-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0142_auto_20230330_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationrequest',
            name='name',
        ),
    ]
