# Generated by Django 3.2.18 on 2023-04-18 02:48

from django.db import migrations, models
import django.db.models.deletion
import leaseslicensing.components.competitive_processes.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0143_merge_0139_auto_20230403_1009_0142_auto_20230330_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveProcessLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, upload_to=leaseslicensing.components.competitive_processes.models.update_competitive_process_comms_log_filename)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leaseslicensing.competitiveprocesslogentry')),
            ],
        ),
    ]
