# Generated by Django 3.2.18 on 2023-04-11 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0144_remove_organisation_delegates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdelegation',
            name='user_full_name',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdelegation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='leaseslicensing.organisation'),
        ),
    ]
