# Generated by Django 3.2.18 on 2023-04-11 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0145_auto_20230411_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationcontact',
            name='is_admin',
        ),
    ]
