# Generated by Django 3.2.18 on 2023-04-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0146_remove_organisationcontact_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
