# Generated by Django 3.2.18 on 2023-04-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0151_auto_20230419_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Group',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='category',
        ),
        migrations.AlterField(
            model_name='proposallocality',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='leaseslicensing.proposal'),
        ),
        migrations.CreateModel(
            name='SubTenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tenure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtenures', to='leaseslicensing.tenure')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenure', 'name')},
            },
        ),
    ]
