# Generated by Django 3.2.18 on 2023-04-21 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0152_auto_20230421_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.group')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.proposal')),
            ],
        ),
    ]
