# Generated by Django 3.2.18 on 2023-04-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0153_proposalgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalgroup',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='leaseslicensing.proposal'),
        ),
        migrations.AlterUniqueTogether(
            name='proposalgroup',
            unique_together={('proposal', 'group')},
        ),
    ]
