# Generated by Django 3.2.18 on 2023-04-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0154_auto_20230421_1517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposallocality',
            unique_together={('proposal', 'district', 'lga')},
        ),
    ]
