# Generated by Django 3.2.18 on 2023-04-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0144_competitiveprocesslogdocument'),
        ('leaseslicensing', '0155_alter_proposallocality_unique_together'),
    ]

    operations = [
    ]
