# Generated by Django 3.2.18 on 2023-05-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0156_merge_20230421_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalSubType',
        ),
    ]
