# Generated by Django 3.2.18 on 2023-04-26 03:49

from django.db import migrations, models
import django.db.models.deletion
import leaseslicensing.components.approvals.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0156_merge_20230421_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalCancellationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('_file', models.FileField(max_length=512, upload_to=leaseslicensing.components.approvals.models.update_approval_cancellation_doc_filename)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_cancellation_documents', to='leaseslicensing.approval')),
            ],
        ),
    ]
