# Generated by Django 3.2.18 on 2023-04-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0158_approvalsurrenderdocument_approvalsuspensiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='original_lease_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
