# Generated by Django 3.2.18 on 2023-04-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0159_approval_original_lease_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='original_lease_number',
            new_name='original_leaselicense_number',
        ),
    ]
