# Generated by Django 3.2.18 on 2023-05-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0162_auto_20230503_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='site_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.sitename'),
        ),
    ]
