# Generated by Django 3.2.18 on 2023-05-05 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0163_proposal_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenures', to='leaseslicensing.proposal')),
                ('tenure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.tenure')),
            ],
            options={
                'unique_together': {('proposal', 'tenure')},
            },
        ),
        migrations.CreateModel(
            name='ProposalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.category')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='leaseslicensing.proposal')),
            ],
            options={
                'unique_together': {('proposal', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProposalAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.act')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='leaseslicensing.proposal')),
            ],
            options={
                'unique_together': {('proposal', 'act')},
            },
        ),
    ]
