# Generated by Django 3.2.18 on 2023-05-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0158_data_migration_approvals_approvaltype'),
        ('leaseslicensing', '0164_proposalact_proposalcategory_proposaltenure'),
    ]

    operations = [
    ]
