# Generated by Django 3.2.18 on 2023-05-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0165_auto_20230508_1446'),
        ('leaseslicensing', '0165_merge_20230508_1422'),
    ]

    operations = [
    ]
