# Generated by Django 3.2.18 on 2023-05-09 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0165_auto_20230508_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vesting', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['vesting'],
            },
        ),
        migrations.CreateModel(
            name='ProposalVesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vestings', to='leaseslicensing.proposal')),
                ('vesting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.vesting')),
            ],
            options={
                'unique_together': {('proposal', 'vesting')},
            },
        ),
        migrations.CreateModel(
            name='ProposalName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.name')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='names', to='leaseslicensing.proposal')),
            ],
            options={
                'unique_together': {('proposal', 'name')},
            },
        ),
    ]
