# Generated by Django 3.2.18 on 2023-05-10 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0166_name_proposalname_proposalvesting_vesting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='vesting',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='vesting',
            old_name='vesting',
            new_name='name',
        ),
        migrations.CreateModel(
            name='ProposalIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.identifier')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='leaseslicensing.proposal')),
            ],
            options={
                'unique_together': {('proposal', 'identifier')},
            },
        ),
    ]
