# Generated by Django 3.2.18 on 2023-05-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0166_merge_20230509_1326'),
        ('leaseslicensing', '0167_auto_20230510_0945'),
    ]

    operations = [
    ]
