# Generated by Django 3.2.18 on 2023-05-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0167_proposalgeometry_drawn_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveprocessgeometry',
            name='drawn_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
