# Generated by Django 3.2.18 on 2023-05-15 06:53

import django.core.files.storage
from django.db import migrations
import leaseslicensing.components.main.models
import leaseslicensing.components.proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0168_merge_20230511_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposallogdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_comms_log_filename),
        ),
    ]
