# Generated by Django 3.2.18 on 2023-05-15 08:51

import django.core.files.storage
from django.db import migrations
import leaseslicensing.components.approvals.models
import leaseslicensing.components.competitive_processes.models
import leaseslicensing.components.compliances.models
import leaseslicensing.components.main.models
import leaseslicensing.components.organisations.models
import leaseslicensing.components.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0169_alter_proposallogdocument__file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallogdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.approvals.models.update_approval_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='competitiveprocesslogdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.competitive_processes.models.update_competitive_process_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='compliancelogdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.compliances.models.update_compliance_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='emailuserlogdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.users.models.email_user_comms_log_document_upload_location),
        ),
        migrations.AlterField(
            model_name='organisationlogdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.organisations.models.update_organisation_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='organisationrequestlogdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.organisations.models.update_organisation_request_comms_log_filename),
        ),
    ]
