# Generated by Django 3.2.18 on 2023-05-16 01:22

import django.core.files.storage
from django.db import migrations
import leaseslicensing.components.main.models
import leaseslicensing.components.organisations.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0170_auto_20230515_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='identification',
            field=leaseslicensing.components.main.models.SecureFileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.organisations.models.organisation_request_identification_upload_path),
        ),
    ]
