# Generated by Django 3.2.18 on 2023-05-16 02:51

import django.core.files.storage
from django.db import migrations
import leaseslicensing.components.approvals.models
import leaseslicensing.components.competitive_processes.models
import leaseslicensing.components.compliances.models
import leaseslicensing.components.main.models
import leaseslicensing.components.proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0171_alter_organisationrequest_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboriginalsitedocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='additionaldocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_additional_doc_filename),
        ),
        migrations.AlterField(
            model_name='approvalcancellationdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.approvals.models.update_approval_cancellation_doc_filename),
        ),
        migrations.AlterField(
            model_name='approvaldocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.approvals.models.update_approval_doc_filename),
        ),
        migrations.AlterField(
            model_name='approvalsurrenderdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.approvals.models.update_approval_surrender_doc_filename),
        ),
        migrations.AlterField(
            model_name='approvalsuspensiondocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.approvals.models.update_approval_suspension_doc_filename),
        ),
        migrations.AlterField(
            model_name='availableactivitiesdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='buildingrequireddocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='capitalinvestmentdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='cashflowdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='clearingvegetationdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='competitiveprocessdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.competitive_processes.models.update_competitive_process_doc_filename),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.compliances.models.update_proposal_compliance_filename),
        ),
        migrations.AlterField(
            model_name='consistentplandocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='consistentpurposedocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='deedpolldocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='environmentallysensitivedocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='exclusiveusedocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='financialcapacitydocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='grounddisturbingworksdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='heritagesitedocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='keymilestonesdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='keypersonneldocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='leaselicenceapprovaldocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='legislativerequirementsdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='longtermusedocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='marketanalysisdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='miningtenementdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='nativetitleconsultationdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='partydetaildocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.competitive_processes.models.update_party_detail_doc_filename),
        ),
        migrations.AlterField(
            model_name='profitandlossdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='proposedapprovaldocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='proposeddeclinedocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='referraldocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_referral_doc_filename),
        ),
        migrations.AlterField(
            model_name='requirementdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_requirement_doc_filename),
        ),
        migrations.AlterField(
            model_name='riskfactorsdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='shapefiledocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='significantchangedocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='staffingdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='wetlandsimpactdocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename),
        ),
    ]
