# Generated by Django 3.2.18 on 2023-05-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0172_auto_20230516_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisationAccessGroup',
        ),
    ]
