# Generated by Django 3.2.18 on 2023-05-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0173_delete_organisationaccessgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='renewal_sent',
            new_name='renewal_notification_sent_to_holder',
        ),
        migrations.AddField(
            model_name='approval',
            name='renewal_review_notification_sent_to_assessors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('current_pending_renewal_review', 'Current (Pending Renewal Review)'), ('current_pending_renewal', 'Current (Pending Renewal)'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended'), ('extended', 'extended'), ('awaiting_payment', 'Awaiting Payment')], default='current', max_length=40),
        ),
    ]
