# Generated by Django 3.2.18 on 2023-05-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0174_auto_20230519_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalact',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='leaseslicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalcategory',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='leaseslicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='proposaldistrict',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='leaseslicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalgroup',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='leaseslicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalidentifier',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='leaseslicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='proposallga',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='leaseslicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalname',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='leaseslicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalregion',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='leaseslicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='proposaltenure',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenures', to='leaseslicensing.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalvesting',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestings', to='leaseslicensing.proposal'),
        ),
    ]
