# Generated by Django 3.2.18 on 2023-05-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0175_auto_20230522_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proponent_reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
