# Generated by Django 3.2.18 on 2023-05-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0176_proposal_proponent_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfeeinvoice',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='bookinginvoice',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='compliancefee',
            name='compliance',
        ),
        migrations.RemoveField(
            model_name='compliancefeeinvoice',
            name='compliance_fee',
        ),
        migrations.DeleteModel(
            name='ApplicationFee',
        ),
        migrations.DeleteModel(
            name='ApplicationFeeInvoice',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingInvoice',
        ),
        migrations.DeleteModel(
            name='ComplianceFee',
        ),
        migrations.DeleteModel(
            name='ComplianceFeeInvoice',
        ),
    ]
