# Generated by Django 3.2.18 on 2023-05-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0168_competitiveprocessgeometry_drawn_by'),
        ('leaseslicensing', '0176_proposal_proponent_reference_number'),
    ]

    operations = [
    ]
