# Generated by Django 3.2.18 on 2023-06-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0177_merge_20230526_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1024, verbose_name='Text body')),
                ('target', models.CharField(max_length=128, verbose_name='Target')),
            ],
            options={
                'verbose_name': 'Details Text',
                'verbose_name_plural': 'Details Texts',
            },
        ),
    ]
