# Generated by Django 3.2.18 on 2023-06-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0178_detailstext'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveprocessgeometry',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalgeometry',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
