# Generated by Django 3.2.18 on 2023-05-25 08:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0179_invoice_oracle_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.invoice')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
