# Generated by Django 3.2.18 on 2023-05-25 08:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0180_invoicetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='leaseslicensing.invoice'),
        ),
    ]
