# Generated by Django 3.2.18 on 2023-05-26 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0181_auto_20230525_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicetransaction',
            options={'ordering': ['datetime_created']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.approval'),
        ),
    ]
