# Generated by Django 3.2.18 on 2023-05-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0182_auto_20230526_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='expiry_notice_sent',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='extended',
        ),
    ]
