# Generated by Django 3.2.18 on 2023-05-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0183_auto_20230529_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='record_management_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
