# Generated by Django 3.2.18 on 2023-06-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0185_auto_20230529_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiveprocess',
            name='lodgement_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='leaseslicensing.approval'),
        ),
    ]
