# Generated by Django 3.2.18 on 2023-06-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0186_auto_20230601_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreviewTempApproval',
        ),
    ]
