# Generated by Django 3.2.18 on 2023-06-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0177_merge_20230526_1424'),
        ('leaseslicensing', '0187_delete_previewtempapproval'),
    ]

    operations = [
    ]
