# Generated by Django 3.2.18 on 2023-06-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0179_auto_20230609_0842'),
        ('leaseslicensing', '0188_merge_20230608_1650'),
    ]

    operations = [
    ]
