# Generated by Django 3.2.18 on 2023-06-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0189_merge_20230613_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationrequest',
            options={'ordering': ['-lodgement_number'], 'verbose_name': 'Organisation Request'},
        ),
        migrations.AlterField(
            model_name='approval',
            name='lodgement_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('current_pending_renewal_review', 'Current (Pending Renewal Review)'), ('current_pending_renewal', 'Current (Pending Renewal)'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended'), ('extended', 'extended'), ('awaiting_payment', 'Awaiting Payment'), ('current_editing_invoicing', 'Current (Editing Invoicing)')], default='current', max_length=40),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='lodgement_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='lodgement_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
