# Generated by Django 3.2.18 on 2023-06-19 01:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0190_auto_20230614_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('current_pending_renewal_review', 'Current (Pending Renewal Review)'), ('current_pending_renewal', 'Current (Pending Renewal)'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended'), ('extended', 'Extended'), ('awaiting_payment', 'Awaiting Payment'), ('current_editing_invoicing', 'Current (Editing Invoicing)')], default='current', max_length=40),
        ),
        migrations.AlterField(
            model_name='detailstext',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
