# Generated by Django 3.2.18 on 2023-06-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0191_remove_externalrefereeinvite_invite_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalrefereeinvite',
            name='sent_by',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalrefereeinvite',
            name='sent_from',
            field=models.SmallIntegerField(choices=[(1, 'Sent From Assessor'), (2, 'Sent From Referral')], default=1),
        ),
        migrations.AlterField(
            model_name='referral',
            name='processing_status',
            field=models.CharField(choices=[('with_referral', 'Pending'), ('recalled', 'Recalled'), ('completed', 'Completed')], default='with_referral', max_length=30, verbose_name='Processing Status'),
        ),
    ]
