# Generated by Django 3.2.18 on 2023-06-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0192_auto_20230616_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalrefereeinvite',
            name='invite_text',
            field=models.TextField(blank=True),
        ),
    ]
