# Generated by Django 3.2.18 on 2023-06-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0193_externalrefereeinvite_invite_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referrer_comment_proposal_details',
            new_name='comment_proposal_details',
        ),
        migrations.RemoveField(
            model_name='proposalassessment',
            name='referrer_comment_additional_documents',
        ),
        migrations.RemoveField(
            model_name='proposalassessment',
            name='referrer_comment_deed_poll',
        ),
        migrations.RemoveField(
            model_name='proposalassessment',
            name='referrer_comment_map',
        ),
        migrations.RemoveField(
            model_name='proposalassessment',
            name='referrer_comment_other',
        ),
        migrations.RemoveField(
            model_name='proposalassessment',
            name='referrer_comment_proposal_details',
        ),
        migrations.RemoveField(
            model_name='proposalassessment',
            name='referrer_comment_proposal_impact',
        ),
        migrations.AddField(
            model_name='referral',
            name='comment_additional_documents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='comment_deed_poll',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='comment_map',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='comment_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='comment_proposal_impact',
            field=models.TextField(blank=True),
        ),
    ]
