# Generated by Django 3.2.18 on 2023-06-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0194_auto_20230619_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ledger_organisation_trading_name',
            field=models.CharField(default='', editable=False, max_length=255, verbose_name='Ledger Organisation Trading Name'),
        ),
    ]
