# Generated by Django 3.2.18 on 2023-06-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0195_organisation_ledger_organisation_trading_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
