# Generated by Django 3.2.18 on 2023-06-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0196_referral_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalassessment',
            name='assessor_comment_general_proposal_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalassessment',
            name='assessor_comment_tourism_proposal_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalassessment',
            name='deficiency_comment_general_proposal_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalassessment',
            name='deficiency_comment_tourism_proposal_details',
            field=models.TextField(blank=True),
        ),
    ]
