# Generated by Django 3.2.18 on 2023-06-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0192_data_migration_details_text'),
        ('leaseslicensing', '0197_auto_20230623_1157'),
    ]

    operations = [
    ]
