# Generated by Django 3.2.18 on 2023-06-27 04:21

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import leaseslicensing.components.compliances.models
import leaseslicensing.components.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0197_auto_20230623_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodged_on', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.IntegerField()),
                ('referral', models.IntegerField()),
                ('is_external', models.BooleanField(default=False)),
                ('linked', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('with_referral', 'Pending'), ('recalled', 'Recalled'), ('completed', 'Completed')], default='with_referral', max_length=30, verbose_name='Processing Status')),
                ('text', models.TextField(blank=True)),
                ('referral_text', models.TextField(blank=True)),
                ('assigned_officer', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-lodged_on',),
            },
        ),
        migrations.AlterField(
            model_name='compliance',
            name='customer_status',
            field=models.CharField(choices=[('due', 'Due'), ('future', 'Future'), ('with_assessor', 'Under Review'), ('approved', 'Approved'), ('discarded', 'Discarded'), ('overdue', 'Overdue')], default='future', max_length=20),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='processing_status',
            field=models.CharField(choices=[('due', 'Due'), ('future', 'Future'), ('with_assessor', 'With Assessor'), ('approved', 'Approved'), ('discarded', 'Discarded'), ('overdue', 'Overdue')], max_length=20),
        ),
        migrations.CreateModel(
            name='ComplianceReferralDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.compliances.models.compliance_referral_document_upload_to)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('compliance_referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_documents', to='leaseslicensing.compliancereferral')),
            ],
            options={
                'ordering': ('compliance_referral', '-uploaded_date'),
            },
        ),
        migrations.AddField(
            model_name='compliancereferral',
            name='compliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='leaseslicensing.compliance'),
        ),
        migrations.CreateModel(
            name='ComplianceAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('submitter', models.IntegerField(blank=True, null=True)),
                ('assessor_comment', models.TextField(blank=True)),
                ('deficiency_comment_map', models.TextField(blank=True)),
                ('compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='leaseslicensing.compliance')),
            ],
        ),
    ]
