# Generated by Django 3.2.18 on 2023-06-27 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0198_auto_20230627_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceassessment',
            name='compliance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='leaseslicensing.compliance'),
        ),
    ]
