# Generated by Django 3.2.18 on 2023-06-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0199_alter_complianceassessment_compliance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complianceassessment',
            old_name='deficiency_comment_map',
            new_name='deficiency_comment',
        ),
    ]
