# Generated by Django 3.2.18 on 2023-07-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0198_merge_20230626_1650'),
        ('leaseslicensing', '0200_rename_deficiency_comment_map_complianceassessment_deficiency_comment'),
    ]

    operations = [
    ]
