# Generated by Django 3.2.18 on 2023-07-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0201_merge_20230703_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='processing_status',
            field=models.CharField(choices=[('due', 'Due'), ('future', 'Future'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('approved', 'Approved'), ('discarded', 'Discarded'), ('overdue', 'Overdue')], max_length=20),
        ),
    ]
