# Generated by Django 3.2.18 on 2023-07-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0203_auto_20230703_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveProcessVesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestings', to='leaseslicensing.competitiveprocess')),
                ('vesting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.vesting')),
            ],
            options={
                'unique_together': {('competitive_process', 'vesting')},
            },
        ),
        migrations.CreateModel(
            name='CompetitiveProcessTenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenures', to='leaseslicensing.competitiveprocess')),
                ('tenure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.tenure')),
            ],
            options={
                'unique_together': {('competitive_process', 'tenure')},
            },
        ),
        migrations.CreateModel(
            name='CompetitiveProcessRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='leaseslicensing.competitiveprocess')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.region')),
            ],
            options={
                'unique_together': {('competitive_process', 'region')},
            },
        ),
        migrations.CreateModel(
            name='CompetitiveProcessName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='leaseslicensing.competitiveprocess')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.name')),
            ],
            options={
                'unique_together': {('competitive_process', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompetitiveProcessLGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='leaseslicensing.competitiveprocess')),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.lga')),
            ],
            options={
                'unique_together': {('competitive_process', 'lga')},
            },
        ),
        migrations.CreateModel(
            name='CompetitiveProcessIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='leaseslicensing.competitiveprocess')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.identifier')),
            ],
            options={
                'unique_together': {('competitive_process', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='CompetitiveProcessDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='leaseslicensing.competitiveprocess')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.district')),
            ],
            options={
                'unique_together': {('competitive_process', 'district')},
            },
        ),
        migrations.CreateModel(
            name='CompetitiveProcessCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.category')),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='leaseslicensing.competitiveprocess')),
            ],
            options={
                'unique_together': {('competitive_process', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CompetitiveProcessAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.act')),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='leaseslicensing.competitiveprocess')),
            ],
            options={
                'unique_together': {('competitive_process', 'act')},
            },
        ),
    ]
