# Generated by Django 3.2.18 on 2023-07-10 03:12

import django.core.files.storage
from django.db import migrations, models
import leaseslicensing.components.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0204_competitiveprocessact_competitiveprocesscategory_competitiveprocessdistrict_competitiveprocessidenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveprocess',
            name='site_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='temporarydocument',
            name='_file',
            field=leaseslicensing.components.main.models.SecureFileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=''),
        ),
    ]
