# Generated by Django 3.2.18 on 2023-07-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0205_auto_20230710_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargemethod',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='consumerpriceindex',
            options={'verbose_name': 'Consumer Price Index', 'verbose_name_plural': 'Consumer Price Indexes'},
        ),
        migrations.AddField(
            model_name='chargemethod',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_details', to='leaseslicensing.approval'),
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='invoicing_once_every',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='review_once_every',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
