# Generated by Django 3.2.18 on 2023-07-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0205_auto_20230710_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationcontact',
            options={'ordering': ('organisation', 'last_name', 'first_name')},
        ),
        migrations.RemoveField(
            model_name='approval',
            name='org_applicant',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='proxy_applicant',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='submitter',
        ),
    ]
