# Generated by Django 3.2.18 on 2023-07-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0206_auto_20230712_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumerpriceindex',
            options={'verbose_name': 'CPI Data', 'verbose_name_plural': 'CPI Data'},
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='cpi_value_q1',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='cpi_value_q2',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='cpi_value_q3',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='cpi_value_q4',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='year',
        ),
        migrations.AddField(
            model_name='consumerpriceindex',
            name='time_period',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerpriceindex',
            name='value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
