# Generated by Django 3.2.18 on 2023-07-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0206_auto_20230719_1505'),
        ('leaseslicensing', '0206_proposalapplicant'),
    ]

    operations = [
    ]
