# Generated by Django 3.2.18 on 2023-08-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0207_merge_0206_auto_20230719_1505_0206_proposalapplicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocument',
            name='reason',
            field=models.CharField(choices=[('new', 'New'), ('amended', 'Amended'), ('renewed', 'Renewed'), ('reissued', 'Reissued'), ('invoicing_updated', 'Invoicing updated')], default='new', max_length=25),
        ),
    ]
