# Generated by Django 3.2.18 on 2023-07-13 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '__first__'),
        ('leaseslicensing', '0207_auto_20230712_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerpriceindex',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='time_period',
            field=models.CharField(help_text='Year and Quarter', max_length=7),
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='value',
            field=models.FloatField(help_text='Percentage Change from Corresponding Quarter of the Previous Year'),
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='invoicing_repetition_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicing_details_set_for_invoicing', to='leaseslicensing.repetitiontype'),
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='review_repetition_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicing_details_set_for_review', to='leaseslicensing.repetitiontype'),
        ),
    ]
