# Generated by Django 3.2.18 on 2023-08-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0208_approvaldocument_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltypedocumenttype',
            name='is_cover_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvaltypedocumenttype',
            name='is_license_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='approvaltypedocumenttype',
            constraint=models.CheckConstraint(check=models.Q(('is_cover_letter', True), ('is_license_document', True), _negated=True), name='either_is_license_document_or_is_cover_letter_or_none'),
        ),
    ]
