# Generated by Django 3.2.18 on 2023-07-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0209_auto_20230713_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicingAndReviewDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.PositiveSmallIntegerField(editable=False)),
                ('invoicing_date_annually', models.DateField(help_text='Invoice every year on')),
                ('invoicing_date_quarterly', models.DateField(help_text='Invoice every quarter (MAR, JUN, SEP, DEC) on')),
                ('invoicing_date_monthly', models.DateField(help_text='Invoice every month on')),
                ('review_date_annually', models.DateField(help_text='Review every year on')),
                ('review_date_quarterly', models.DateField(help_text='Review every quarter (MAR, JUN, SEP, DEC) on')),
                ('review_date_monthly', models.DateField(help_text='Review every month on')),
            ],
            options={
                'verbose_name_plural': 'Invoicing and Review Dates',
            },
        ),
        migrations.AlterModelOptions(
            name='cpicalculationmethod',
            options={'verbose_name': 'CPI Calculation Method', 'verbose_name_plural': 'CPI Calculation Methods'},
        ),
    ]
