# Generated by Django 3.2.18 on 2023-07-14 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0210_auto_20230714_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicingandreviewdates',
            options={'ordering': ['year'], 'verbose_name_plural': 'Invoicing and Review Dates'},
        ),
        migrations.RemoveField(
            model_name='invoicingandreviewdates',
            name='invoicing_date_monthly',
        ),
        migrations.RemoveField(
            model_name='invoicingandreviewdates',
            name='invoicing_date_quarterly',
        ),
        migrations.RemoveField(
            model_name='invoicingandreviewdates',
            name='review_date_monthly',
        ),
        migrations.RemoveField(
            model_name='invoicingandreviewdates',
            name='review_date_quarterly',
        ),
        migrations.AddField(
            model_name='invoicingandreviewdates',
            name='invoicing_day_for_month',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='invoicingandreviewdates',
            name='invoicing_day_for_quarter',
            field=models.PositiveSmallIntegerField(default=1, help_text='Invoice every quarter (MAR, JUN, SEP, DEC) on', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='invoicingandreviewdates',
            name='review_day_for_month',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='invoicingandreviewdates',
            name='review_day_for_quarter',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
