# Generated by Django 3.2.18 on 2023-08-11 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0210_alter_approvaldocument_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='sign_off_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_off_sheet', to='leaseslicensing.approvaldocument'),
        ),
    ]
