# Generated by Django 3.2.18 on 2023-07-14 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0211_auto_20230714_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='value',
            field=models.DecimalField(decimal_places=1, help_text='Percentage Change from Corresponding Quarter of the Previous Year', max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoicingandreviewdates',
            name='invoicing_day_for_quarter',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of the month to generate and send invoices every quarter (MAR, JUN, SEP, DEC)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='invoicingandreviewdates',
            name='review_day_for_quarter',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of the month to send review reminder every quarter (MAR, JUN, SEP, DEC)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
