# Generated by Django 3.2.18 on 2023-08-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0211_approval_sign_off_sheet'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvaltypedocumenttype',
            name='either_is_license_document_or_is_cover_letter_or_none',
        ),
        migrations.AddField(
            model_name='approvaltypedocumenttype',
            name='is_sign_off_sheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='approvaltypedocumenttype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_cover_letter', True), ('is_license_document', True), _negated=True), models.Q(('is_license_document', True), ('is_sign_off_sheet', True), _negated=True), models.Q(('is_cover_letter', True), ('is_sign_off_sheet', True), _negated=True)), name='only_one_or_none_of_license_document_cover_letter_sign_off_sheet'),
        ),
    ]
