# Generated by Django 3.2.18 on 2023-08-16 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0212_auto_20230811_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='leaseslicensing.approval'),
        ),
    ]
