# Generated by Django 3.2.18 on 2023-08-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0213_alter_proposal_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldocument',
            name='reason',
            field=models.CharField(choices=[('new', 'New'), ('amended', 'Amended'), ('renewed', 'Renewed'), ('reissued', 'Reissued'), ('invoicing_updated', 'Invoicing updated')], default='new', max_length=25),
        ),
    ]
