# Generated by Django 3.2.18 on 2023-07-18 02:18
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Invoice = apps.get_model("leaseslicensing", "Invoice")
    for row in Invoice.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0214_auto_20230718_1009'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),        
    ]
