# Generated by Django 3.2.18 on 2023-08-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0215_approval_lodgement_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='replaced_by',
        ),
    ]
