# Generated by Django 3.2.18 on 2023-07-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0219_approvaltype_invoices_exclude_gst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvaltype',
            old_name='invoices_exclude_gst',
            new_name='invoice_amount_includes_gst',
        ),
    ]
