# Generated by Django 3.2.18 on 2023-07-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0220_rename_invoices_exclude_gst_approvaltype_invoice_amount_includes_gst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvaltype',
            old_name='invoice_amount_includes_gst',
            new_name='gst_free',
        ),
    ]
