# Generated by Django 3.2.18 on 2023-07-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0223_invoice_proponent_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicingdetails',
            name='approval',
        ),
        migrations.AddField(
            model_name='percentageofgrossturnover',
            name='gross_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
