# Generated by Django 3.2.18 on 2023-07-28 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0224_auto_20230720_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumerpriceindex',
            options={'verbose_name': 'CPI Data (Perth - All Groups)', 'verbose_name_plural': 'CPI Data (Perth - All Groups)'},
        ),
        migrations.AlterModelOptions(
            name='repetitiontype',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='fixedannualincrementpercentage',
            name='increment_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default='0.0', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='percentageofgrossturnover',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default='0.0', max_digits=4, null=True),
        ),
    ]
