# Generated by Django 3.2.18 on 2023-07-31 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0227_auto_20230728_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateTimeField(null=True),
        ),
    ]
