# Generated by Django 3.2.18 on 2023-07-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0228_auto_20230731_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_due',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('pending_upload_oracle_invoice', 'Pending Upload of Oracle Invoice'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('void', 'Void')], default='pending_upload_oracle_invoice', max_length=40, null=True),
        ),
    ]
