# Generated by Django 3.2.18 on 2023-08-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0229_auto_20230731_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicingdetails',
            name='invoicing_quarters_start_month',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True),
        ),
    ]
