# Generated by Django 3.2.18 on 2023-08-01 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0230_invoicingdetails_invoicing_quarters_start_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='invoicing_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='leaseslicensing.invoicingdetails'),
        ),
    ]
