# Generated by Django 3.2.18 on 2023-08-02 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0231_alter_proposal_invoicing_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCPIYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=1, default='0.0', max_digits=4, null=True)),
                ('invoicing_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_cpi_years', to='leaseslicensing.invoicingdetails')),
            ],
        ),
    ]
