# Generated by Django 3.2.18 on 2023-08-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0207_merge_0206_auto_20230719_1505_0206_proposalapplicant'),
        ('leaseslicensing', '0232_customcpiyear'),
    ]

    operations = [
    ]
