# Generated by Django 3.2.18 on 2023-08-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0235_approvaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstandardrequirement',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
