# Generated by Django 3.2.18 on 2023-08-08 02:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0236_alter_proposalstandardrequirement_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('gross_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='leaseslicensing.percentageofgrossturnover')),
            ],
            options={
                'ordering': ['year', 'quarter'],
            },
        ),
    ]
