# Generated by Django 3.2.18 on 2023-08-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0237_financialquarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcpiyear',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
