# Generated by Django 3.2.18 on 2023-08-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0239_auto_20230811_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpicalculationmethod',
            name='quarter',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
