# Generated by Django 3.2.18 on 2023-08-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0240_cpicalculationmethod_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedannualincrementpercentage',
            name='increment_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default='0.0', max_digits=4, null=True),
        ),
    ]
