# Generated by Django 3.2.18 on 2023-08-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0241_alter_fixedannualincrementpercentage_increment_percentage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixedannualincrementamount',
            unique_together={('year', 'invoicing_details')},
        ),
        migrations.AlterUniqueTogether(
            name='fixedannualincrementpercentage',
            unique_together={('year', 'invoicing_details')},
        ),
    ]
