# Generated by Django 3.2.18 on 2023-08-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0246_auto_20230821_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalapplicant',
            name='postal_same_as_residential',
            field=models.BooleanField(default=False),
        ),
    ]
