# Generated by Django 3.2.18 on 2023-08-22 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0247_alter_proposalapplicant_postal_same_as_residential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaldocumenttype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='additionaldocumenttype',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposaladditionaldocumenttype',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_document_types', to='leaseslicensing.proposal'),
        ),
    ]
