# Generated by Django 3.2.18 on 2023-08-22 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0248_auto_20230822_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldocument',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='additionaldocument',
            name='input_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='additionaldocument',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='additionaldocument',
            name='proposal_additional_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='leaseslicensing.proposaladditionaldocumenttype'),
        ),
    ]
