# Generated by Django 3.2.18 on 2023-08-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0216_remove_approval_replaced_by'),
        ('leaseslicensing', '0251_invoice_date_paid'),
    ]

    operations = [
    ]
