# Generated by Django 3.2.18 on 2023-08-25 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0251_invoice_date_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliance',
            name='fee_invoice_reference',
        ),
    ]
