# Generated by Django 3.2.18 on 2023-08-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0252_remove_compliance_fee_invoice_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='gross_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proposalstandardrequirement',
            name='gross_turnover_required',
            field=models.BooleanField(default=False),
        ),
    ]
