# Generated by Django 3.2.18 on 2023-08-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0252_merge_20230824_1408'),
        ('leaseslicensing', '0254_remove_proposalstandardrequirement_participant_number_required'),
    ]

    operations = [
    ]
