# Generated by Django 3.2.18 on 2023-08-31 06:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0255_merge_20230828_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(9999)])),
                ('gross_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='leaseslicensing.percentageofgrossturnover')),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
    ]
