# Generated by Django 3.2.18 on 2023-09-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0257_proposalapplicant_emailuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentageofgrossturnover',
            name='estimated_gross_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='percentageofgrossturnover',
            name='gross_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
