# Generated by Django 3.2.18 on 2023-09-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0258_auto_20230904_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaseLicenceFee',
        ),
    ]
