# Generated by Django 3.2.18 on 2023-09-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0260_scheduledinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalassessment',
            old_name='assessor_comment_other',
            new_name='assessor_comment_gis_data',
        ),
        migrations.RenameField(
            model_name='proposalassessment',
            old_name='deficiency_comment_other',
            new_name='deficiency_comment_gis_data',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='comment_other',
            new_name='comment_gis_data',
        ),
        migrations.AddField(
            model_name='proposalassessment',
            name='assessor_comment_categorisation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalassessment',
            name='deficiency_comment_categorisation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='comment_categorisation',
            field=models.TextField(blank=True),
        ),
    ]
