# Generated by Django 3.2.18 on 2023-09-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0261_auto_20230906_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date_updated',
            new_name='datetime_updated',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_due',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_paid',
            field=models.DateField(null=True),
        ),
    ]
