# Generated by Django 3.2.18 on 2023-09-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0263_invoice_ad_hoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='oracle_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
