# Generated by Django 3.2.21 on 2023-09-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0264_alter_invoice_oracle_invoice_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequiredDocument',
        ),
    ]
