# Generated by Django 3.2.21 on 2023-09-13 04:42

from django.db import migrations

def update_proposal_prefix(apps, schema_editor):
    Proposal = apps.get_model("leaseslicensing", "Proposal")
    for proposal in Proposal.objects.all():
        proposal.lodgement_number = proposal.lodgement_number.replace("A", "P")
        proposal.save()

class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0266_alter_invoicingdetails_review_once_every'),
    ]

    operations = [
        migrations.RunPython(update_proposal_prefix),
    ]
