# Generated by Django 3.2.21 on 2023-09-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0267_auto_20230913_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledinvoice',
            old_name='attempts_to_send_internal_email',
            new_name='attempts_to_send_notification_email',
        ),
        migrations.RenameField(
            model_name='scheduledinvoice',
            old_name='internal_email_sent',
            new_name='notification_email_sent',
        ),
        migrations.RemoveField(
            model_name='scheduledinvoice',
            name='attempts_to_send_external_email',
        ),
        migrations.RemoveField(
            model_name='scheduledinvoice',
            name='external_email_sent',
        ),
    ]
