# Generated by Django 3.2.21 on 2023-09-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0268_auto_20230914_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledinvoice',
            old_name='generated_from',
            new_name='invoicing_details',
        ),
    ]
