# Generated by Django 3.2.21 on 2023-09-14 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0269_rename_generated_from_scheduledinvoice_invoicing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='scheduled_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='leaseslicensing.scheduledinvoice'),
        ),
    ]
