# Generated by Django 3.2.21 on 2023-09-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0270_invoice_scheduled_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledinvoice',
            name='invoice_has_been_generated',
        ),
    ]
