# Generated by Django 3.2.21 on 2023-09-15 04:18

from django.core.management import call_command
from django.db import migrations

fixture = "default_standard_requirements"

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='leaseslicensing')

class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0271_remove_scheduledinvoice_invoice_has_been_generated'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
