# Generated by Django 3.2.21 on 2023-10-04 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0272_auto_20230915_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalstandardrequirement',
            options={'verbose_name': 'Proposal Standard Requirement', 'verbose_name_plural': 'Proposal Standard Requirements'},
        ),
        migrations.CreateModel(
            name='ApprovalTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodgement_number', models.CharField(max_length=9, unique=True)),
                ('processing_status', models.CharField(choices=[('draft', 'Draft'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='draft', max_length=40)),
                ('transferee', models.IntegerField(blank=True, null=True)),
                ('approval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='leaseslicensing.approval')),
            ],
            options={
                'ordering': ('-lodgement_number',),
            },
        ),
    ]
