# Generated by Django 3.2.21 on 2023-10-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0272_auto_20230915_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalstandardrequirement',
            options={'verbose_name': 'Proposal Standard Requirement', 'verbose_name_plural': 'Proposal Standard Requirements'},
        ),
    ]
