# Generated by Django 3.2.21 on 2023-10-04 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0273_auto_20231004_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltransfer',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvaltransfer',
            name='datetime_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvaltransfer',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
