# Generated by Django 3.2.21 on 2023-10-04 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0274_auto_20231004_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltransfer',
            name='approval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='leaseslicensing.approval'),
            preserve_default=False,
        ),
    ]
