# Generated by Django 3.2.21 on 2023-10-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0275_alter_approvaltransfer_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltransfer',
            name='lodgement_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
