# Generated by Django 3.2.21 on 2023-10-04 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0276_alter_approvaltransfer_lodgement_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltransfer',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='leaseslicensing.approval'),
        ),
    ]
