# Generated by Django 3.2.21 on 2023-10-04 03:35

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import leaseslicensing.components.approvals.models
import leaseslicensing.components.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0277_alter_approvaltransfer_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalTransferDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', leaseslicensing.components.main.models.SecureFileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.approvals.models.supporting_documents_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('approval_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='leaseslicensing.approvaltransfer')),
            ],
            options={
                'verbose_name': 'Approval Transfer Supporting Document',
            },
        ),
    ]
