# Generated by Django 3.2.21 on 2023-10-04 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0278_approvaltransferdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltransferdocument',
            name='approval_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_transfer_supporting_documents', to='leaseslicensing.approvaltransfer'),
        ),
    ]
