# Generated by Django 3.2.21 on 2023-10-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0279_alter_approvaltransferdocument_approval_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltransfer',
            name='transferee_type',
            field=models.CharField(choices=[('organisation', 'Organisation'), ('individual', 'Individual')], default='organisation', max_length=12),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='name',
            field=models.CharField(choices=[('registration_of_interest', 'Registration of Interest'), ('lease_licence', 'Lease Licence'), ('lease_licence_transfer', 'Lease Licence Transfer')], max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='approvaltransfer',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='draft', max_length=10),
        ),
    ]
