# Generated by Django 3.2.21 on 2023-10-05 02:13

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0280_auto_20231004_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalTransferApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailuser_id', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='Given name(s)')),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('residential_line1', models.CharField(blank=True, max_length=255, verbose_name='Line 1')),
                ('residential_line2', models.CharField(blank=True, max_length=255, verbose_name='Line 2')),
                ('residential_line3', models.CharField(blank=True, max_length=255, verbose_name='Line 3')),
                ('residential_locality', models.CharField(blank=True, max_length=255, verbose_name='Suburb / Town')),
                ('residential_state', models.CharField(blank=True, default='WA', max_length=255)),
                ('residential_country', django_countries.fields.CountryField(blank=True, default='AU', max_length=2)),
                ('residential_postcode', models.CharField(blank=True, max_length=10)),
                ('postal_same_as_residential', models.BooleanField(default=False)),
                ('postal_line1', models.CharField(blank=True, max_length=255, verbose_name='Line 1')),
                ('postal_line2', models.CharField(blank=True, max_length=255, verbose_name='Line 2')),
                ('postal_line3', models.CharField(blank=True, max_length=255, verbose_name='Line 3')),
                ('postal_locality', models.CharField(blank=True, max_length=255, verbose_name='Suburb / Town')),
                ('postal_state', models.CharField(blank=True, default='WA', max_length=255)),
                ('postal_country', django_countries.fields.CountryField(blank=True, default='AU', max_length=2)),
                ('postal_postcode', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number')),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile number')),
                ('approval_transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='leaseslicensing.approvaltransfer')),
            ],
        ),
    ]
