# Generated by Django 3.2.21 on 2023-10-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0281_approvaltransferapplicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltransferapplicant',
            name='approval_transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='leaseslicensing.approvaltransfer'),
        ),
    ]
