# Generated by Django 3.2.21 on 2023-10-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0282_alter_approvaltransferapplicant_approval_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltransfer',
            name='initiator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
