# Generated by Django 3.2.21 on 2023-10-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0283_approvaltransfer_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltransfer',
            name='datetime_initiated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
