# Generated by Django 3.2.21 on 2023-10-09 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0284_approvaltransfer_datetime_initiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='transfer_approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.approval'),
        ),
    ]
