# Generated by Django 3.2.21 on 2023-10-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0285_proposal_transfer_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='transfer_approval',
        ),
    ]
