# Generated by Django 3.2.21 on 2023-10-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0273_alter_proposalstandardrequirement_options'),
        ('leaseslicensing', '0286_remove_proposal_transfer_approval'),
    ]

    operations = [
    ]
