# Generated by Django 3.2.21 on 2023-10-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0256_alter_approvaltype_approvaltypedocumenttypes'),
        ('leaseslicensing', '0287_merge_20231012_1656'),
    ]

    operations = [
    ]
