# Generated by Django 3.2.21 on 2023-10-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0288_merge_20231013_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldocument',
            name='reason',
            field=models.CharField(choices=[('new', 'New'), ('amended', 'Amended'), ('renewed', 'Renewed'), ('reissued', 'Reissued'), ('invoicing_updated', 'Invoicing updated'), ('transferred', 'Transferred')], default='new', max_length=25),
        ),
    ]
