# Generated by Django 3.2.21 on 2023-10-25 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0289_alter_approvaldocument_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltypedocumenttypeonapprovaltype',
            name='approval_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvaltype_approvaltypedocumenttypes', to='leaseslicensing.approvaltype'),
        ),
    ]
