# Generated by Django 3.2.21 on 2023-10-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0289_alter_approvaldocument_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewDateAnnually',
        ),
        migrations.DeleteModel(
            name='ReviewDateMonthly',
        ),
        migrations.DeleteModel(
            name='ReviewDateQuarterly',
        ),
    ]
