# Generated by Django 3.2.21 on 2023-10-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0290_auto_20231025_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoicingDateAnnually',
        ),
        migrations.DeleteModel(
            name='InvoicingDateMonthly',
        ),
        migrations.DeleteModel(
            name='InvoicingDateQuarterly',
        ),
    ]
