# Generated by Django 3.2.21 on 2023-10-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0291_auto_20231025_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoicingAndReviewDates',
        ),
    ]
