# Generated by Django 3.2.21 on 2023-10-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0292_delete_invoicingandreviewdates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendmentreason',
            options={'verbose_name': 'Proposal Amendment Reason', 'verbose_name_plural': 'Proposal Amendment Reasons'},
        ),
        migrations.AlterModelOptions(
            name='applicationtype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Proposal Category', 'verbose_name_plural': 'Proposal Categories'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
        migrations.AlterField(
            model_name='proposal',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_assessor_conditions', 'With Assessor (Conditions)'), ('with_approver', 'With Approver'), ('with_referral', 'With Referral'), ('with_referral_conditions', 'With Referral (Conditions)'), ('approved_registration_of_interest', 'Approved (Registration of Interest)'), ('approved_competitive_process', 'Approved (Competitive Process)'), ('approved_editing_invoicing', 'Approved (Editing Invoicing)'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='draft', max_length=35, verbose_name='Processing Status'),
        ),
    ]
