# Generated by Django 3.2.21 on 2023-10-27 01:23

from django.db import migrations


def migrate_proposal_processing_status(apps, schema_editor):
    Proposal = apps.get_model("leaseslicensing", "Proposal")
    for proposal in Proposal.objects.all():
        if proposal.processing_status == "approved_application":
            proposal.processing_status = "approved_registration_of_interest"           
            proposal.save(update_fields=["processing_status"])    

class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0293_auto_20231026_1719'),
    ]

    operations = [
        migrations.RunPython(migrate_proposal_processing_status, atomic=True),
    ]
