# Generated by Django 3.2.21 on 2023-10-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0290_alter_approvaltypedocumenttypeonapprovaltype_approval_type'),
        ('leaseslicensing', '0294_migrate_proposal_processing_status'),
    ]

    operations = [
    ]
