# Generated by Django 3.2.21 on 2023-10-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0295_merge_20231030_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalstandardrequirement',
            options={'verbose_name': 'Proposal Standard Condition', 'verbose_name_plural': 'Proposal Standard Conditions'},
        ),
    ]
