# Generated by Django 3.2.21 on 2023-10-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0296_alter_proposalstandardrequirement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtype',
            name='name',
            field=models.CharField(choices=[('registration_of_interest', 'Registration of Interest'), ('lease_licence', 'Lease Licence')], max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_assessor_conditions', 'With Assessor (Conditions)'), ('with_approver', 'With Approver'), ('with_referral', 'With Referral'), ('approved_registration_of_interest', 'Approved (Registration of Interest)'), ('approved_competitive_process', 'Approved (Competitive Process)'), ('approved_editing_invoicing', 'Approved (Editing Invoicing)'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='draft', max_length=35, verbose_name='Processing Status'),
        ),
    ]
