# Generated by Django 3.2.21 on 2023-11-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0297_auto_20231030_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='original_leaselicense_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
