# Generated by Django 3.2.21 on 2023-11-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0298_proposal_original_leaselicense_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='added_internally',
            field=models.BooleanField(default=False),
        ),
    ]
