# Generated by Django 3.2.23 on 2023-11-22 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0301_auto_20231122_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='competitive_process_to_copy_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_added', to='leaseslicensing.competitiveprocess'),
        ),
    ]
