# Generated by Django 3.2.23 on 2023-12-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0302_proposal_competitive_process_to_copy_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentageofgrossturnover',
            name='estimate_locked',
            field=models.BooleanField(default=False),
        ),
    ]
