# Generated by Django 3.2.23 on 2023-12-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0305_auto_20231218_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
    ]
