# Generated by Django 3.2.23 on 2023-12-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0307_auto_20231219_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSystemSettings',
        ),
    ]
