# Generated by Django 3.2.23 on 2024-01-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0308_delete_usersystemsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaldocumenttype',
            options={'ordering': ['name'], 'verbose_name': 'Additional Document Type'},
        ),
        migrations.AlterModelOptions(
            name='complianceamendmentreason',
            options={'verbose_name': 'Compliance Amendment Reason'},
        ),
        migrations.AlterModelOptions(
            name='sitename',
            options={'ordering': ['name'], 'verbose_name': 'Site Name'},
        ),
    ]
