# Generated by Django 3.2.23 on 2024-01-17 06:42

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import leaseslicensing.components.competitive_processes.models
import leaseslicensing.components.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0310_auto_20240115_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPShapefileDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', leaseslicensing.components.main.models.SecureFileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media', location='/home/oak/dev/leases-licensing/protected_media'), upload_to=leaseslicensing.components.competitive_processes.models.update_competitive_process_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_documents', to='leaseslicensing.competitiveprocess')),
            ],
        ),
    ]
