# Generated by Django 3.2.23 on 2024-01-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0311_cpshapefiledocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='shapefile_json',
        ),
    ]
