# Generated by Django 3.2.23 on 2024-01-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0312_remove_proposal_shapefile_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiveprocess',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('in_progress', 'In Progress (Unlocked)'), ('discarded', 'Discarded'), ('completed_application', 'Completed (Application)'), ('completed_declined', 'Completed (Declined)')], default='in_progress', max_length=30, verbose_name='Status'),
        ),
    ]
