# Generated by Django 3.2.23 on 2024-01-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0312_remove_proposal_shapefile_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalrefereeinvite',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
