# Generated by Django 3.2.23 on 2024-01-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0313_externalrefereeinvite_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalrefereeinvite',
            name='sent_from',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='sent_from',
        ),
    ]
