# Generated by Django 3.2.23 on 2024-01-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0314_auto_20240124_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtype',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='oracle_code_application',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='oracle_code_licence',
        ),
    ]
