# Generated by Django 3.2.23 on 2024-01-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0315_auto_20240125_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OracleCode',
        ),
    ]
