# Generated by Django 3.2.23 on 2024-01-25 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0317_oraclecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='oracle_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.oraclecode'),
        ),
        migrations.AddField(
            model_name='invoicingdetails',
            name='oracle_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicing_details', to='leaseslicensing.oraclecode'),
        ),
    ]
