# Generated by Django 3.2.23 on 2024-01-31 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0318_auto_20240125_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrownLandRentReviewDate',
        ),
    ]
