# Generated by Django 3.2.23 on 2024-01-31 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0314_alter_competitiveprocess_status'),
        ('leaseslicensing', '0318_auto_20240125_1527'),
    ]

    operations = [
    ]
