# Generated by Django 3.2.23 on 2024-01-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0320_remove_compliance_num_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('pending_upload_oracle_invoice', 'Pending Upload of Oracle Invoice'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('void', 'Void'), ('discarded', 'Discarded')], default='pending_upload_oracle_invoice', max_length=40, null=True),
        ),
    ]
