# Generated by Django 3.2.23 on 2024-02-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0319_merge_20240131_1107'),
        ('leaseslicensing', '0321_alter_invoice_status'),
    ]

    operations = [
    ]
