# Generated by Django 3.2.23 on 2024-02-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0322_merge_20240201_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveprocessgeometry',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proposalgeometry',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
