# Generated by Django 3.2.23 on 2024-02-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0323_auto_20240202_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitiveprocessgeometry',
            old_name='source',
            new_name='source_name',
        ),
        migrations.RenameField(
            model_name='proposalgeometry',
            old_name='source',
            new_name='source_name',
        ),
        migrations.AddField(
            model_name='competitiveprocessgeometry',
            name='source_type',
            field=models.CharField(blank=True, choices=[('applicant', 'Applicant'), ('assessor', 'Assessor'), ('competitive_process_editor', 'Competitive Process Editor')], max_length=255),
        ),
        migrations.AddField(
            model_name='proposalgeometry',
            name='source_type',
            field=models.CharField(blank=True, choices=[('applicant', 'Applicant'), ('assessor', 'Assessor'), ('competitive_process_editor', 'Competitive Process Editor')], max_length=255),
        ),
    ]
