# Generated by Django 3.2.23 on 2024-02-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0324_auto_20240202_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiveprocessgeometry',
            name='source_type',
            field=models.CharField(blank=True, choices=[('proponent', 'Proponent'), ('assessor', 'Assessor'), ('competitive_process_editor', 'Competitive Process Editor')], max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalgeometry',
            name='source_type',
            field=models.CharField(blank=True, choices=[('proponent', 'Proponent'), ('assessor', 'Assessor'), ('competitive_process_editor', 'Competitive Process Editor')], max_length=255),
        ),
    ]
