# Generated by Django 3.2.23 on 2024-02-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0325_auto_20240205_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='ledger_organisation_trading_name',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='Ledger Organisation Trading Name'),
        ),
    ]
